Repository PSBicep/PSBicep, pull requests merged in 2021-12, with the labels that each got.

#222 Update Update-BicepCLI.md
  Docs/Help/Update-BicepCLI.md
Labels: bugFix

#229 Update-BicepTypes is not removing types anymore
  Source/Public/Update-BicepTypes.ps1
  Tests/Get-BicepApiReference.Tests.ps1
  Tests/Update-BicepTypes.Tests.ps1
  scripts/downloadDependencies.ps1
Labels: bugFix

#230 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: skipReleaseNotes

#232 Workflow step "Publish test results" now continues on error
  .github/workflows/RunTests.yaml
Labels: skipReleaseNotes

#231 Replaced "!" with "-not"
  Source/Private/ConvertToHashtable.ps1
  Source/Public/Convert-JsonToBicep.ps1
  Source/Public/Install-BicepCLI.ps1
  Source/Public/New-BicepParameterFile.ps1
  Source/Public/Uninstall-BicepCLI.ps1
  Source/Public/Update-BicepCLI.ps1
  Source/Public/Update-BicepParameterFile.ps1
  scripts/mergedPRDetailsToReleaseDraft.ps1
Labels: skipReleaseNotes

#227 Implement v.0.4.1008 support
  Docs/Help/Build-Bicep.md
  Docs/Help/Publish-Bicep.md
  Docs/Help/Restore-Bicep.md
  Source/Bicep.psd1
  Source/Public/Build-Bicep.ps1
  Source/Public/Publish-Bicep.ps1
  Source/Public/Restore-Bicep.ps1
  Source/en-US/Bicep-help.xml
  Tests/Publish-Bicep.Tests.ps1
  Tests/Restore-Bicep.Tests.ps1
  Tests/supportFiles/workingBicep.bicep
  scripts/downloadDependencies.ps1
Labels: newFeature

#238 Added tests and improved testrunner
  .github/workflows/RunTests.yaml
  Source/Private/ConvertToHashtable.ps1
  Tests/ConvertToHashTable.Tests.ps1
  Tests/ListBicepVersions.Tests.ps1
  Tests/TestRunner.ps1
Labels: skipReleaseNotes

#233 Updated module version to 2.1.0
  Docs/bicep-version-comparison.md
  README.md
  Source/Bicep.psd1
  scripts/downloadDependencies.ps1
Labels: skipReleaseNotes
