Repository PSBicep/PSBicep, pull requests merged in 2021-05, with the labels that each got.

#138 Added -RequiredVersion 5.1.1 when importing Pester
  .github/workflows/RunTests.yaml
Labels: bugFix

#130 Added parameter -OutputPath
  Docs/Help/Build-Bicep.md
  Docs/Help/Convert-JsonToBicep.md
  Source/Public/Build-Bicep.ps1
  Source/en-US/Bicep-help.xml
Labels: enhancement

#140 Added New-BicepParameterFile
  Docs/Help/New-BicepParameterFile.md
  Source/Bicep.psd1
  Source/Public/New-BicepParameterFile.ps1
  Source/en-US/Bicep-help.xml
Labels: newFeature

#143 Added a default value for int params
  Source/Private/GenerateParameterFile.ps1
Labels: bugFix

#141 Updated module to version 1.4.6
  README.md
  Source/Bicep.psd1
Labels: skipReleaseNotes

#146 Added new version available function to all public functions
  Source/Public/Build-Bicep.ps1
  Source/Public/Convert-JsonToBicep.ps1
  Source/Public/ConvertTo-Bicep.ps1
  Source/Public/Get-BicepApiReference.ps1
  Source/Public/Get-BicepVersion.ps1
  Source/Public/Install-BicepCLI.ps1
  Source/Public/New-BicepParameterFile.ps1
  Source/Public/Uninstall-BicepCLI.ps1
  Source/Public/Update-BicepCLI.ps1
  Source/Public/Update-BicepTypes.ps1
Labels: enhancement

#148 Updated to CreateWithAzTypes() method for AzResourceTypeProvider
  Source/Private/ParseBicep.ps1
  Source/Public/Convert-JsonToBicep.ps1
  Source/Public/ConvertTo-Bicep.ps1
Labels: bugFix

#134 New command Convert-BicepParamsToDecoratorStyle
  Docs/Help/Build-Bicep.md
  Docs/Help/Convert-BicepParamsToDecoratorStyle.md
  Source/Bicep.psd1
  Source/Private/ConvertToHashtable.ps1
  Source/Private/ParseBicep.ps1
  Source/Public/Build-Bicep.ps1
  Source/Public/Convert-BicepParamsToDecoratorStyle.ps1
  Source/en-US/Bicep-help.xml
Labels: newFeature

#144 Added options for generate parameter file
  Docs/Help/Build-Bicep.md
  Docs/Help/New-BicepParameterFile.md
  Source/Private/GenerateParameterFile.ps1
  Source/Public/Build-Bicep.ps1
  Source/Public/New-BicepParameterFile.ps1
  Source/en-US/Bicep-help.xml
Labels: enhancement

#149 Version 1.4.7 prep
  README.md
  Source/Bicep.psd1
  Source/assemblyversion.txt
Labels: skipReleaseNotes

#150 changed version in shield
  README.md
Labels: skipReleaseNotes

#151 Fixed bug in Convert-JsonToBicep after update ConvertToHashtable.ps1 change
  Source/Public/Convert-JsonToBicep.ps1
Labels: bugFix

#152 Fix ConvertToHashTable empty or single value arrays
  Source/Private/ConvertToHashtable.ps1
Labels: bugFix

#153 Updated version number to 1.4.7
  README.md
Labels: skipReleaseNotes

#162 Removed required version from Pester
  .github/workflows/RunTests.yaml
Labels: bugFix

#161 Use LocalPath instead of AbsolutePath
  Source/Public/ConvertTo-Bicep.ps1
Labels: bugFix

#160 Added -Path to Convert-JsonToBicep
  Docs/Help/Convert-JsonToBicep.md
  Source/Public/Convert-JsonToBicep.ps1
  Source/en-US/Bicep-help.xml
Labels: newFeature
