Repository PSBicep/PSBicep, pull requests merged in 2021-07, with the labels that each got.

#199 Additional tests for Get-BicepApiReference
  Tests/Get-BicepApiReference.Tests.ps1
Labels: skipReleaseNotes

#196 Added try/catch to hide error msg
  Source/Public/ConvertTo-Bicep.ps1
Labels: bugFix

#201 Updated no files found message in ConvertTo-Bicep
  Source/Public/ConvertTo-Bicep.ps1
Labels: bugFix

#194 Bicep net
  .github/workflows/RunTests.yaml
  .gitignore
  Source/Bicep.psd1
  Source/Classes/10.BicepDiagnosticLevel.ps1
  Source/Classes/20.BicepDiagnosticEntry.ps1
  Source/Private/ParseBicep.ps1
  Source/Private/TestModuleVersion.ps1
  Source/Private/WriteBicepDiagnostic.ps1
  Source/Private/WriteBicepNetDiagnostic.ps1
  Source/Public/Build-Bicep.ps1
  Source/Public/Convert-JsonToBicep.ps1
  Source/Public/ConvertTo-Bicep.ps1
  Source/Public/New-BicepParameterFile.ps1
  Source/Public/Test-BicepFile.ps1
  Source/assemblyversion.txt
  Source/build.psd1
  scripts/downloadDependencies.ps1
Labels: enhancement

#203 Prepped for pre-release version
  README.md
  Source/Bicep.psd1
Labels: skipReleaseNotes

#204 Added support for pre-release to template metadata
  Source/Public/Build-Bicep.ps1
Labels: enhancement

#207 Added version comparison to docs
  Docs/bicep-version-comparison.md
Labels: skipReleaseNotes

#206 #187 - Add force flag to prevent unexpected overwrite of files.
  Docs/Help/ConvertTo-Bicep.md
  Source/Public/ConvertTo-Bicep.ps1
Labels: 2.0, enhancement

#208 Updated contributing guide with info about BicepNet
  CONTRIBUTING.md
Labels: skipReleaseNotes

#210 New/Update-Parameter file now validates the Bicep template
  Source/Public/New-BicepParameterFile.ps1
  Source/Public/Update-BicepParameterFile.ps1
Labels: bugFix

#212 Updated pre-release tag in module manifest
  Source/Bicep.psd1
Labels: skipReleaseNotes

#215 Updated external help file
  Docs/Help/ConvertTo-Bicep.md
  Source/en-US/Bicep-help.xml
Labels: skipReleaseNotes

#217 Updated all links to PSBicep/PSBicep
  CONTRIBUTING.md
  Docs/Help/Build-Bicep.md
  Docs/Help/ConvertTo-Bicep.md
  Docs/Help/Get-BicepVersion.md
  Docs/Help/Install-BicepCLI.md
  Docs/Help/Update-BicepCLI.md
  Source/Private/TestModuleVersion.ps1
  Source/en-US/Bicep-help.xml
  scripts/mergedPRDetailsToReleaseDraft.ps1
Labels: skipReleaseNotes

#218 Updated readme
  README.md
Labels: skipReleaseNotes
