Repository PSBicep/PSBicep, pull requests merged in 2021-06, with the labels that each got.

#167 Prepared support for Bicep 0.4.1
  .github/workflows/RunTests.yaml
  Source/Bicep.psd1
  Source/assemblyversion.txt
  scripts/downloadDependencies.ps1
Labels: enhancement

#169 TestModuleVersion now only warns when current module is older
  Source/Private/TestModuleVersion.ps1
Labels: enhancement

#158 Added -ToClipboard to Convert-JsonToBicep + Docs
  Docs/Help/Convert-JsonToBicep.md
  Source/Public/Convert-JsonToBicep.ps1
  Source/en-US/Bicep-help.xml
Labels: newFeature

#168 Decommissioned Convert-BicepParamsToDecorators
  Docs/Help/Convert-BicepParamsToDecoratorStyle.md
  README.md
  Source/Public/Convert-BicepParamsToDecoratorStyle.ps1
  Source/en-US/Bicep-help.xml
Labels: enhancement

#172 Updated version to 1.5.0
  README.md
  Source/Bicep.psd1
Labels: skipReleaseNotes

#175 Added tests for Get-BicepApiReference
  Tests/Get-BicepApiReference.Tests.ps1
Labels: enhancement

#176 Publish test result
  .github/workflows/RunTests.yaml
  Tests/TestRunner.ps1
Labels: skipReleaseNotes

#177 Initial tests for Get-BicepVersion
  Tests/Get-BicepVersion.Tests.ps1
Labels: skipReleaseNotes

#164 Added test for Build-Bicep
  Tests/Build-Bicep.Tests.ps1
  Tests/supportFiles/bicepconfig.json
  Tests/supportFiles/brokenBicep.bicep
  Tests/supportFiles/workingBicep.bicep
Labels: enhancement

#173 Update bicep parameter file #159
  Docs/Help/Update-BicepParameterFile.md
  Source/Bicep.psd1
  Source/Public/Update-BicepParameterFile.ps1
  Source/en-US/Bicep-help.xml
Labels: newFeature

#185 Added function Test-BicepFile
  Docs/Help/Test-BicepFile.md
  Source/Bicep.psd1
  Source/Private/ParseBicep.ps1
  Source/Private/WriteBicepDiagnostic.ps1
  Source/Public/Test-BicepFile.ps1
  Source/en-US/Bicep-help.xml
Labels: newFeature

#181 Typo fix in ParseBicep message
  Source/Private/ListBicepVersions.ps1
  Source/Private/ParseBicep.ps1
  Source/Public/Get-BicepApiReference.ps1
Labels: bugFix

#186 [DO NOT MERGE] Version 1.5.1 bump
  README.md
  Source/Bicep.psd1
Labels: skipReleaseNotes

#188 Fix #180
  Source/Public/ConvertTo-Bicep.ps1
Labels: bugFix

#189 Add Parameters parameter to Update-BicepParameterFile
  Source/Public/Update-BicepParameterFile.ps1
Labels: enhancement

#192 Update-BicepParameterFile fixes
  Source/Public/New-BicepParameterFile.ps1
  Source/Public/Update-BicepParameterFile.ps1
Labels: bugFix

#195 General improvements for tests
  Source/Bicep.psm1
  Tests/Build-Bicep.Tests.ps1
  Tests/CompareBicepVersion.Tests.ps1
  Tests/Get-BicepApiReference.Tests.ps1
  Tests/Get-BicepVersion.Tests.ps1
  Tests/Install-BicepBuild.Tests.ps1
  Tests/InstalledBicepVersion.Tests.ps1
  Tests/ListBicepVersions.Tests.ps1
  Tests/Module.tests.ps1
  Tests/TestBicep.Tests.ps1
  Tests/TestRunner.ps1
Labels: skipReleaseNotes
