Repository PSBicep/PSBicep, pull requests merged in 2021-03, with the labels that each got.

#70 fixed typo in build-bicep help file
  Docs/Help/Build-Bicep.md
Labels: documentation

#100 Get-BicepApiReference improvements
  Source/Public/Get-BicepApiReference.ps1
Labels: enhancement

#101 Install-BicepCLI no longer throws file locked error
  Source/Public/Install-BicepCLI.ps1
Labels: bugFix

#99 Added Update-BicepTypes to readme
  README.md
Labels: enhancement

#102 Renamed downloadAssemblies.ps1 to downloadDependencies.ps1
  .github/workflows/RunTests.yaml
  scripts/downloadDependencies.ps1
Labels: enhancement
