Repository PSBicep/PSBicep, pull requests merged in 2021-04, with the labels that each got.

#106 New command Convert-JsonToBicep
  Docs/Help/Convert-JsonToBicep.md
  Source/Bicep.psd1
  Source/Public/Convert-JsonToBicep.ps1
  Source/en-US/Bicep-help.xml
Labels: newFeature

#115 Convert-JsonToBicep: Use safe path for tmp/temp and allow pipeline input
  Docs/Help/Convert-JsonToBicep.md
  Source/Public/Convert-JsonToBicep.ps1
Labels: bugFix

#122 fix: Error message on Windows-only commands for Mac/Linux
  Docs/Help/Install-BicepCLI.md
  Docs/Help/Uninstall-BicepCLI.md
  Docs/Help/Update-BicepCLI.md
  Source/Public/Install-BicepCLI.ps1
  Source/Public/Uninstall-BicepCLI.ps1
  Source/Public/Update-BicepCLI.ps1
  Source/en-US/Bicep-help.xml
Labels: bugFix

#114 Fix Convert-JsonToBicep sort order
  Source/Private/ConvertToHashtable.ps1
  Source/Public/Convert-JsonToBicep.ps1
  Source/en-US/Bicep-help.xml
Labels: bugFix

#124 Moved tests folder
  Tests/CompareBicepVersion.Tests.ps1
  Tests/Install-BicepBuild.Tests.ps1
  Tests/InstalledBicepVersion.Tests.ps1
  Tests/ListBicepVersions.Tests.ps1
  Tests/Module.tests.ps1
  Tests/TestBicep.Tests.ps1
Labels: skipReleaseNotes

#121 Added action that verifies PR labels
  .github/workflows/requireLabels.yml
Labels: enhancement

#118 Added contribution guride
  CONTRIBUTING.md
  README.md
Labels: updatedDocs

#126 Fixed broken link in readme
  README.md
Labels: skipReleaseNotes

#127 fixed another broken link
  CONTRIBUTING.md
Labels: skipReleaseNotes

#129 removed "-" from documentation
  Docs/Help/Build-Bicep.md
  Source/en-US/Bicep-help.xml
Labels: updatedDocs

#132 Added new maintainer to readme
  README.md
Labels: updatedDocs
