Repository PSBicep/PSBicep, pull requests merged in 2022-09, with the labels that each got.

#272 Added new command `Get-BicepConfig`
  Docs/Help/Get-BicepConfig.md
  Source/Bicep.psd1
  Source/Public/Get-BicepConfig.ps1
  Tests/Get-BicepConfig.Tests.ps1
Labels: newFeature

#278 Added verbose message about bicepconfig.json in use
  .bicepNetVersion
  Source/Public/Build-Bicep.ps1
  Source/Public/Publish-Bicep.ps1
  Source/Public/Restore-Bicep.ps1
  Source/Public/Test-BicepFile.ps1
Labels: enhancement

#279 Updated help for `Get-BicepConfig`
  Docs/Help/Get-BicepConfig.md
  Source/en-US/Bicep-help.xml
Labels: skipReleaseNotes

#281 Add wait for file handle to be released
  Tests/Get-BicepConfig.Tests.ps1
Labels: bugFix

#280 Updated for version 2.3.2
  Docs/bicep-version-comparison.md
  README.md
  Source/Bicep.psd1
Labels: skipReleaseNotes
