Repository PSBicep/PSBicep, pull requests merged in 2022-04, with the labels that each got.

#249 Implemented Find-BicepModule
  Docs/Help/Find-BicepModule.md
  Source/Bicep.psd1
  Source/Public/Find-BicepModule.ps1
  Tests/Find-BicepModule.Tests.ps1
Labels: newFeature

#251 Added PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: skipReleaseNotes

#254 Removed `IgnoreDiagnostics` from `Build-Bicep` to support new BicepNet versions
  Docs/Help/Build-Bicep.md
  Source/Private/ParseBicep.ps1
  Source/Public/Build-Bicep.ps1
  Source/en-US/Bicep-help.xml
  Tests/Build-Bicep.Tests.ps1
  scripts/downloadDependencies.ps1
Labels: enhancement

#253 Added Clear-BicepModuleCache
  Docs/Help/Clear-BicepModuleCache.md
  Source/Bicep.psd1
  Source/Public/Clear-BicepModuleCache.ps1
  Tests/Clear-BicepModuleCache.Tests.ps1
Labels: newFeature
