Repository PSBicep/PSBicep, pull requests merged in 2023-06, with the labels that each got.

#290 Fix tests on WSL
  Tests/Build-Bicep.Tests.ps1
  Tests/Clear-BicepModuleCache.Tests.ps1
  Tests/CompareBicepVersion.Tests.ps1
  Tests/Convert-JsonToBicep.Tests.ps1
  Tests/ConvertTo-Bicep.Tests.ps1
  Tests/ConvertToHashTable.Tests.ps1
  Tests/Find-BicepModule.Tests.ps1
  Tests/Get-BicepApiReference.Tests.ps1
  Tests/Get-BicepConfig.Tests.ps1
  Tests/Get-BicepMetadata.Tests.ps1
  Tests/Get-BicepVersion.Tests.ps1
  Tests/InstalledBicepVersion.Tests.ps1
  Tests/ListBicepVersions.Tests.ps1
  Tests/Module.tests.ps1
  Tests/New-BicepParameterFile.Tests.ps1
  Tests/Publish-Bicep.Tests.ps1
  Tests/Restore-Bicep.Tests.ps1
  Tests/TestBicep.Tests.ps1
  Tests/Update-BicepTypes.Tests.ps1
Labels: bugFix

#291 Feature/add linux test to build workflow
  .github/workflows/RunTests.yaml
Labels: enhancement

#303 Export commands `Export-BicepResource` and `Export-BicepChildResource`
  Docs/Help/Build-Bicep.md
  Docs/Help/Clear-BicepModuleCache.md
  Docs/Help/Convert-JsonToBicep.md
  Docs/Help/ConvertTo-Bicep.md
  Docs/Help/Export-BicepChildResource.md
  Docs/Help/Export-BicepResource.md
  Docs/Help/Get-BicepApiReference.md
  Docs/Help/Get-BicepConfig.md
  Docs/Help/Get-BicepMetadata.md
  Docs/Help/Get-BicepVersion.md
  Docs/Help/Install-BicepCLI.md
  Docs/Help/New-BicepParameterFile.md
  Docs/Help/Test-BicepFile.md
  Docs/Help/Uninstall-BicepCLI.md
  Docs/Help/Update-BicepCLI.md
  Docs/Help/Update-BicepParameterFile.md
  Docs/Help/Update-BicepTypes.md
  Source/Bicep.psd1
  Source/Public/Export-BicepChildResource.ps1
  Source/Public/Export-BicepResource.ps1
Labels: enhancement

#308 Fixes issue 307
  Source/Public/Clear-BicepModuleCache.ps1
Labels: bugFix

#305 Add Build-BicepParam support
  Docs/Help/Build-Bicep.md
  Docs/Help/Build-BicepParam.md
  Source/Bicep.psd1
  Source/Public/Build-BicepParam.ps1
Labels: newFeature

#310 New command `Format-BicepFile`
  Docs/Help/Format-BicepFile.md
  Source/Bicep.psd1
  Source/Public/Format-BicepFile.ps1
Labels: newFeature

#301 V2.4.0 release prep
  .bicepNetVersion
  .github/workflows/RunTests.yaml
  Source/Bicep.psd1
  Source/Public/Build-Bicep.ps1
  Source/Public/Get-BicepMetadata.ps1
  Source/Public/New-BicepParameterFile.ps1
  Tests/Get-BicepConfig.Tests.ps1
Labels: skipReleaseNotes

#312 2 4 0 preview
  Docs/bicep-version-comparison.md
  README.md
Labels: skipReleaseNotes

#313 Added `Format-BicepFile` preview command to readme
  README.md
Labels: documentation
