Repository PSBicep/PSBicep, pull requests merged in 2024-01, with the labels that each got.

#293 Bicep markdown documentation
  Docs/Help/Get-BicepApiReference.md
  Docs/Help/New-BicepMarkdownDocumentation.md
  Source/Bicep.psd1
  Source/Private/New-MDMetadata.ps1
  Source/Private/New-MDModules.ps1
  Source/Private/New-MDOutputs.ps1
  Source/Private/New-MDParameters.ps1
  Source/Private/New-MDProviders.ps1
  Source/Private/New-MDResources.ps1
  Source/Private/New-MDTableHeader.ps1
  Source/Private/New-MDVariables.ps1
  Source/Public/Get-BicepApiReference.ps1
  Source/Public/Get-UsedModulesInBicepFile.ps1
  Source/Public/New-BicepMarkdownDocumentation.ps1
  Source/en-US/Bicep-help.xml
  Tests/Build-Bicep.Tests.ps1
  Tests/Get-BicepMetadata.Tests.ps1
  Tests/Get-UsedModulesInBicepFile.Tests.ps1
  Tests/New-BicepMarkdownDocumentation.Tests.ps1
  Tests/New-MDMetadata.Tests.ps1
  Tests/New-MDModules.Tests.ps1
  Tests/New-MDOutputs.Tests.ps1
  Tests/New-MDParameters.Tests.ps1
  Tests/New-MDProviders.Tests.ps1
  Tests/New-MDResources.Tests.ps1
  Tests/New-MDTableHeader.ps1
  Tests/New-MDVariables.Tests.ps1
  Tests/Publish-Bicep.Tests.ps1
  Tests/supportFiles/bicepWithMeta.bicep
  Tests/supportFiles/workingBicep.bicep
Labels: newFeature

#224 Draft: New bicep markdown documentation
  Docs/Help/Get-BicepApiReference.md
  Docs/Help/New-BicepMarkdownDocumentation.md
  Source/Bicep.psd1
  Source/Public/Get-BicepApiReference.ps1
  Source/Public/New-BicepMarkdownDocumentation.ps1
  Source/en-US/Bicep-help.xml
Labels: newFeature

#329 New parameter `-Force` for `Publish-Bicep`
  Docs/Help/Build-BicepParam.md
  Docs/Help/Publish-Bicep.md
  Source/Public/Publish-Bicep.ps1
  Source/en-US/Bicep-help.xml
Labels: enhancement, dependency: BicepNet

#332 Fixes release workflow to load latest PowerShellForGitHub version
  .github/workflows/build.yml
Labels: bugFix

#333 Configuration for `gitversion` for `main` instead of `master`
  GitVersion.yml
Labels: bugFix

#334 Change gitversion mode
  GitVersion.yml
Labels: bugFix
