Repository PSBicep/PSBicep, pull requests merged in 2025-06, with the labels that each got.

#361 Use independent classes for each function
  Docs/Help/Get-BicepApiVersion.md
  Docs/Help/Search-AzureResourceGraph.md
  PSBicep.Core/BicepHelper.cs
  PSBicep.Core/BicepService.cs
  PSBicep.Core/BicepWrapper.Build.cs
  PSBicep.Core/BicepWrapper.ConvertResourceToBicep.cs
  PSBicep.Core/BicepWrapper.Decompile.cs
  PSBicep.Core/BicepWrapper.FindModule.cs
  PSBicep.Core/BicepWrapper.Format.cs
  PSBicep.Core/BicepWrapper.Publish.cs
  PSBicep.Core/BicepWrapper.Restore.cs
  PSBicep.Core/BicepWrapper.cs
  PSBicep.Core/Models/BicepResourceTypeReference.cs
  PSBicep.Core/PSBicep.Core.sln
  PSBicep.Core/ServiceCollectionExtensions.cs
  PSBicep.Core/Services/BicepCoreService.cs
  PSBicep.Core/Services/BicepRegistryService.cs
  PSBicep.sln
  PSBicep/Commands/BaseCommand.cs
  PSBicep/Commands/BuildBicepFileCommand.cs
  PSBicep/Commands/BuildBicepParamFileCommand.cs
  PSBicep/Commands/ConvertARMResourceToBicepCommand.cs
  PSBicep/Commands/ConvertToBicepFileCommand.cs
  PSBicep/Commands/FindBicepModuleCommand.cs
  PSBicep/Commands/FormatBicepFile.cs
  PSBicep/Commands/GetBicepApiVersion.cs
  PSBicep/Commands/GetBicepCachePathCommand.cs
  PSBicep/Commands/GetBicepConfigCommand.cs
  PSBicep/Commands/GetBicepVersionCommand.cs
  PSBicep/Commands/PublishBicepFileCommand.cs
  PSBicep/Commands/ResolveBicepResourceTypeCommand.cs
  PSBicep/Commands/RestoreBicepFileCommand.cs
  Source/Bicep.psd1
  Source/Private/GetAzResourceGraphPage.ps1
  Source/Private/Search-AzureResourceGraph.ps1
  Source/Public/Export-BicepResource.ps1
  Tests/Restore-Bicep.Tests.ps1
  build.ps1
  scripts/downloadDependencies.ps1
Labels: enhancement

#366 Fixed typo and info in readme
  README.md
Labels: skipReleaseNotes

#367 Fix #364 by implementing a singleton of the BicepService
  PSBicep.Core/BicepService.cs
  PSBicep.Core/Logging/DiagnosticLogger.cs
  PSBicep.Core/ServiceCollectionExtensions.cs
  PSBicep.Core/Services/BicepCoreService.cs
  PSBicep.Core/Services/BicepRegistryService.cs
  PSBicep/Commands/BaseCommand.cs
  PSBicep/LoadContext/BicepLoader.cs
Labels: bugFix
